# Generated by Django 5.1.3 on 2025-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_comment_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.CharField(max_length=10),
        ),
    ]
