# Generated by Django 5.1.3 on 2025-01-03 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.DateField(verbose_name=datetime.date(2026, 1, 3)),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
