# Generated by Django 5.1.3 on 2025-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_amount_alter_post_period_alter_post_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='empty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
