# Generated by Django 5.1.3 on 2025-01-04 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comment_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.DateField(verbose_name=datetime.date(2026, 1, 4)),
        ),
    ]
