# Generated by Django 5.1.3 on 2025-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_city_alter_post_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Self Pickup', 'Self Pickup')], default='Courier', max_length=20),
        ),
    ]
