# Generated by Django 5.1.3 on 2025-01-07 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='period',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
        ),
    ]
