# Generated by Django 5.1.3 on 2025-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_comment_user_alter_review_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('All Genders', 'All Genders'), ('Men', 'Men'), ('Women', 'Women')], default='All Genders', max_length=20),
        ),
    ]
